/** 与 `in_app_notifications.category` 对齐的稳定枚举，供客户端筛选与测试断言。 */
export const InAppNotificationCategory = {
  CONTENT_REDEEM_SUCCESS: 'CONTENT_REDEEM_SUCCESS',
  CONTENT_MODERATION_APPROVED: 'CONTENT_MODERATION_APPROVED',
  CONTENT_MODERATION_REJECTED: 'CONTENT_MODERATION_REJECTED',
  CONTENT_MODERATION_SUSPICIOUS: 'CONTENT_MODERATION_SUSPICIOUS',
} as const;
